[package]
name = "taro-shop-rust"
version = "0.1.0"
authors = ["summersnake"]
edition = "2021"

[dependencies]
sqlx = { version = "0.6.0", features = ["runtime-actix-native-tls", "mysql"] }
actix-web = "4.1.0"
actix-rt = "2.7.0"
serde = "1.0.140"
serde_json = "1.0.82"
uuid = { version = "1.1.2", features = ["serde", "v4"] }
