[package]
name = "taro_shop_rust"
version = "0.1.0"
authors = ["summersnake"]
edition = "2021"

[dependencies]
sqlx = { version = "0.6.0", features = ["runtime-tokio-rustls", "mysql"] }
tokio = { version = "1.11.0", features = ["full"] }
axum = { version = "0.2.3" }
serde = { version = "1.0", features = ["derive"] }
tower = { version = "0.4", features = ["util", "timeout"] }
tower-http = { version = "0.1", features = ["add-extension", "trace"] }
